# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shahrukh Ahmed Siddiqui
email: shahrukh.amd@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Computer Science Enthusiast
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://sasiddiqui.com" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: shahrukhamd
github_username:  shahrukhamd
facebook_username: shahrukhamd
stack_username: shahrukhamd
google_plus_username: shahrukhamd

# Address information
address_street: 3034 Melrose Place
address_city: Beverly Hills
address_state: CA
address_zip: 90201

# Build settings
markdown: kramdown
